DROP TABLE person;
CREATE TABLE person (
	name TEXT PRIMARY KEY
);
INSERT INTO person VALUES ('Harry Marr');
INSERT INTO person VALUES ('Stuart Gale');
INSERT INTO person VALUES ('Kris Jenkins');
INSERT INTO person VALUES ('Lee Turner');
INSERT INTO person VALUES ('Drew Neil');
INSERT INTO person VALUES ('Christopher Harrison');
INSERT INTO person VALUES ('Matt Southerden');
INSERT INTO person VALUES ('Alex');
INSERT INTO person VALUES ('Tomasz Jureczko');
INSERT INTO person VALUES ('John Slade');
INSERT INTO person VALUES ('Zack Voase');
INSERT INTO person VALUES ('Mark Burns');
INSERT INTO person VALUES ('Sam Patterson');
INSERT INTO person VALUES ('Beau Martínez');
INSERT INTO person VALUES ('Sweet');
INSERT INTO person VALUES ('Daniel Lucraft');
INSERT INTO person VALUES ('Nasir Jamal');
INSERT INTO person VALUES ('Tom Brand');
INSERT INTO person VALUES ('Ben Hall');
INSERT INTO person VALUES ('Tom Rees');
INSERT INTO person VALUES ('Matt Saunders');
INSERT INTO person VALUES ('Ed Robinson');
INSERT INTO person VALUES ('Jack Franklin');
INSERT INTO person VALUES ('Kajetan Bo');
INSERT INTO person VALUES ('Hakan Ensari');
INSERT INTO person VALUES ('david');
INSERT INTO person VALUES ('Vivien Barousse');
INSERT INTO person VALUES ('Tom Parker');
INSERT INTO person VALUES ('Christopher Reeves');
INSERT INTO person VALUES ('Alex Young');
INSERT INTO person VALUES ('Benjamin Johnson');
INSERT INTO person VALUES ('Damon Davison');
INSERT INTO person VALUES ('Toni Lopez');
INSERT INTO person VALUES ('Robin Tweedie');
INSERT INTO person VALUES ('Allan');
INSERT INTO person VALUES ('Paul Nasrat');
INSERT INTO person VALUES ('Felix');
INSERT INTO person VALUES ('John Plummer');
INSERT INTO person VALUES ('Claudio Ortolina');
INSERT INTO person VALUES ('Emile Swarts');
INSERT INTO person VALUES ('Tudor Prodan');
INSERT INTO person VALUES ('Alan Oliver');
INSERT INTO person VALUES ('Dave King');
INSERT INTO person VALUES ('Ben Taylor');
INSERT INTO person VALUES ('Oliver Nightingale');
INSERT INTO person VALUES ('Chris Patuzzo');
INSERT INTO person VALUES ('Jan Harasym');
INSERT INTO person VALUES ('Matt');
INSERT INTO person VALUES ('Łukasz Korecki');
INSERT INTO person VALUES ('chrisr');
INSERT INTO person VALUES ('Steve Martin');
